package org.example.clinicservice.entity.enums;

public enum AdminRole {
    SYSTEM_ADMINISTRATOR,
    DEPARTMENT_ADMINISTRATOR,
    USER_MANAGEMENT_ADMINISTRATOR,
    DATA_ANALYSIS_ADMINISTRATOR,
    REPORTING_ADMINISTRATOR,
    PRIVACY_AND_SECURITY_ADMINISTRATOR

}
